---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hrcbl2gu4ork/public_html/
    # Step 1: Deploy Frontend files
    - /bin/cp -R Frontend/* $DEPLOYPATH
    # Step 2: Navigate to the Backend directory
    - cd Backend
    # Step 3: Install backend dependencies
    - /usr/local/bin/npm install
    # Step 4: Start the Backend server
    - /usr/local/bin/npm start
